version: '3.4'

services:

  broker:
    image: eclipse-mosquitto
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./var/mosquitto/data:/mosquitto/data
      - ./var/mosquitto/log:/mosquitto/log
      - ./etc/mosquitto/config:/mosquitto/config

  cpop:
    image: cognitivexr/cpop:cuda-11
    command: python3 -m cpop.cli.detector
    environment:
      - CPOP_CAMERA_MODEL
      - CPOP_BROKER_HOST=broker
    devices:
      - ${CPOP_CAMERA_DEVICE:-/dev/video0}:/dev/video0
    volumes:
      - ${CPOP_PROPERTIES:-./etc/cpop}:/root/.cpop
